### ISSUE TITLE
run ./cve-workaround no output

### ISSUE THREAD

**Issue by crazycen** [blake-fm/vcenter-log4j#2]
root@vc [ /tmp ]# ./cve-workaround
root@vc [ /tmp ]#

**Comment by blake-fm** [comment]
Hiya, try the instructions at https://github.com/blake-fm/vcenter-log4j#quick-and-dirty - it's all that's needed.

**Comment by crazycen** [comment]
i try sh cve-workaround ,have error!
root@vc [ /tmp ]# sh cve-workaround 
cve-workaround: line 22: `cve-workaround': not a valid identifier

**Comment by blake-fm** [comment]
Did you check the instructions I linked?  You just need to copy / paste the entire contents of the script into an SSH session with bash running.  I linked the raw output so it was easier - it's all functions.

Then type `cve`, press tab, then press enter.

Shouldn't be any ./cve-workaround or sh cve-workaround or anything else required.

**Comment by crazycen** [comment]
My fault! OK now! Thank you for your work !

**Comment by blake-fm** [comment]
Phew!  Glad to hear.  =)
